format_strings = true

match_block_trailing_comma = true

max_width = 80

reorder_impl_items = true

report_fixme = "Always"

report_todo = "Always"

wrap_comments = true

struct_field_align_threshold = 20