#!/bin/bash
export MOD_HOST_PEDAL_DIR='/home/patch/ModHostPedal'
export PATH_MI_ROOT='/home/patch/ModHostPedal'
export JACK_PROMISCUOUS_SERVER=jack
export LV2_PATH=/usr/modep/lv2

# ## Flash the LED.  Arguments: Duration Frequency Count
LED_FLASH=$MOD_HOST_PEDAL_DIR/led_flash

`$LED_FLASH 2 .1 2`

sudo killall mod-host
service modep-mod-host start
service modep-mod-ui start

`$LED_FLASH 2 .1 4`
