#!/bin/bash
export MOD_HOST_PEDAL_DIR='/home/patch/ModHostPedal'
export PATH_MI_ROOT='/home/patch/ModHostPedal'
export JACK_PROMISCUOUS_SERVER=jack
export LV2_PATH=/usr/modep/lv2
# ## Flash the LED.  Arguments: Duration Frequency Count
LED_FLASH=$MOD_HOST_PEDAL_DIR/led_flash

`$LED_FLASH 2 0.5 2 `

service modep-mod-host stop
sudo killall mod-host

MOD_HOST_EXE='/home/patch/mod-host/bin/mod-host '
rm -f /tmp/mod-host.pid
runuser  --preserve-environment -u patch  -- $MOD_HOST_EXE 

runuser  --preserve-environment -u patch $MOD_HOST_PEDAL_DIR/process_modep.pl

runuser  --preserve-environment -u patch   $MOD_HOST_PEDAL_DIR/driver & 
`$LED_FLASH 2 0.5 3 `





